### ISSUE TITLE
加入 markdown lint

### ISSUE THREAD

**Issue by chuanxd** [cepave-f2e/vue-owl-ui#24]
https://github.com/mivok/markdownlint

follow https://guides.github.com/features/mastering-markdown/

**Comment by rwu823** [comment]
`gem` out

**Comment by rwu823** [comment]
後來想一想， 覺得我們應該不需要 `markdown lint`，markdown 只是表現式的語言，不像程式富有邏輯，而且還要花時間 review 適合我們的 rule 與更改舊有的，不知大家意下如何？ @CApopsicle @chuanxd

**Comment by chuanxd** [comment]
舉個例子
大標題 `#` 後面沒有空白，這個在 gihub markdown parser 是不會變成 H1 的

透過 lint 讓程式輔助這種費時細節避免一些 merge 後的修改

**Comment by chuanxd** [comment]
先關
