### ISSUE TITLE
[DualList] it should be supported case-sensitive

### ISSUE THREAD

**Issue by rwu823** [cepave-f2e/vue-owl-ui#82]
- Add `sensitive` in filter props options

**Comment by CApopsicle** [comment]
字串裡面大寫字有match的搜尋結果也要 `highlight` 嗎 🤔 

![2016-12-12 2 00 29](https://cloud.githubusercontent.com/assets/5334755/21089499/7a4428a2-c073-11e6-8e08-e6ebc885aec4.png)

**Comment by chuanxd** [comment]
要呀
