### ISSUE TITLE
[DualList] Add support api query

### ISSUE THREAD

**Issue by rwu823** [cepave-f2e/vue-owl-ui#85]
- 如果是空的，還是這麼大好像怪怪的？
![image](https://cloud.githubusercontent.com/assets/890063/21093579/b649b6ea-c0a6-11e6-9c30-d75ab837cc76.png)
- 新增打 api 功能

**Comment by CApopsicle** [comment]
可以把它壓扁! 我只有設一個固定高度而已因為要捲動
給`<Dual />` width就好

![2016-12-12 5 58 05](https://cloud.githubusercontent.com/assets/5334755/21095021/a235a1c6-c094-11e6-85f4-fa6cfe3254c0.png)

**Comment by rwu823** [comment]
喔喔 我是指高度 QQ
