### ISSUE TITLE
[DualList] item 文字過長需加入 ...

### ISSUE THREAD

**Issue by rwu823** [cepave-f2e/vue-owl-ui#90]
![image](https://cloud.githubusercontent.com/assets/890063/21486267/6e534d6e-cc05-11e6-8b6d-c88004455921.png)

**Comment by CApopsicle** [comment]
用 `...` 那想要看到全部的文字怎麼辦QQ

**Comment by chuanxd** [comment]
tooltip

**Comment by CApopsicle** [comment]
感覺有點多餘 有些過長有些沒有過長@@
如果這種情況沒有很多
我覺得可以先過長變成 `...` 然後先統一把字縮小

**Comment by chuanxd** [comment]
應該說這是一種情況，所以考慮的是如何讓 user 看到完整的資訊

**Comment by rwu823** [comment]
可以先簡單用 `title` 屬性來解決？
